//Generated by Firebase:

// Import the functions needed from the SDKs I need
import { initializeApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries


// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: "[CENSORED]",
  authDomain: "[CENSORED]",
  projectId: "[CENSORED]",
  storageBucket: "[CENSORED]",
  messagingSenderId: "[CENSORED]",
  appId: "[CENSORED]",
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);

// Initialize Firestore and export it
export const db = getFirestore(app);
